[CHANGE] coding style steps 9

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,12 +1,13 @@
+git@github.com:EpitechPromo2027/B-DOP-200-LYN-2-1-chocolatine-safia.beaumale-mesmar
 name: chocolatine
 
 on:
   push:
     branches-ignore:
-    - "ga-ignore-*"
+      - 'ga-ignore-*'
   pull_request:
     branches-ignore:
-    - "ga-ignore-*"
+      - 'ga-ignore-*'
 
 env:
   MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-LYN-2-1-chocolatine-safia.beaumale-mesmar"
@@ -14,49 +15,52 @@ env:
   ARGUMENTS: ""
 
 jobs:
-  coding_style:
-    name: "Regarder si le repo contient des erreurs de normes"
+  check_repo:
+    name: "Checks if the repository is clean and void of any unwanted files (temp files, binary files, etc.)"
     runs-on: ubuntu-latest
-    container: 
+    container:
       image: ghcr.io/epitech/coding-style-checker:latest
-    
+
     steps:
       - uses: actions/checkout@v3
-      - id: coding_style
+      - id: check_repo
         run: |
-          check.sh $(pwd) $(pwd);
-          if [[ -s coding-style-reports.log ]]; then
-            exit 1;
-          fi;
-          exit 0;
-          echo "::set-output name=number_of_errors::$(grep -c 'Error' coding_style_reports.log)"
+          UNWANTED_FILES=$(find . -type f -not -path "./git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.so" -or -name "*.gcno" -or -name "*.gcda" -or -name "*#" -or -name "#*" -or -name "*.gcov" -or -name "*pain_au_chocolat*")
+          for FILES in $UNWANTED_FILES; do
+            echo "::error file=${FILES#./},title=Unwanted file detected::${FILES#./}"
+          done
+          if [[ -n $UNWANTED_FILES ]]
+          then
+            exit 1
+          else
+            echo No unwanted files detected
+          fi
 
-
-  compilation:
-    needs: [coding_style]
-    name: "Checks compilation of binaries given !"
+  check_program_compilation:
+    needs: [check_repo]
+    name: "Checks if make compil and test all binary listed in the ARGUMENTS variable"
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker:latest
 
     steps:
       - uses: actions/checkout@v3
-      - id: compilation
-      - run: make
+      - id: check_program_compilation
+        run: make
         timeout-minutes: 2
       - run: make clean
       - run: |
-          OIFS=$IFS
-          IFS=','
+          OIFS = $IFS
+          IFS = ','
           for x in $EXECUTABLES
             do
               ./$x $ARGUMENTS
             done
           IFS=$OIFS
 
-  run_tests:
-    needs: [compilation]
-    name: "Runs criterion tests !"
+run_tests:
+    needs: [check_program_compilation]
+    name: "Runs tests with criterion"
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker:latest
@@ -70,7 +74,7 @@ jobs:
   push_to_mirror:
     needs: [run_tests]
     if: ${{ github.event_name == 'push' }}
-    name: "Push files to given mirror repo !"
+    name: "Push all files to mirror specified"
     runs-on: ubuntu-latest
 
     steps:
