[CHANGE] coding style steps 8

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -24,16 +24,12 @@ jobs:
       - uses: actions/checkout@v3
       - id: coding_style
         run: |
-          UNWANTED_FILES=$(find . -type f -not -path "./git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.so" -or -name "*.gcno" -or -name "*.gcda" -or -name "*#" -or -name "#*" -or -name "*.gcov" -or -name "*pain_au_chocolat*")
-          for FILES in $UNWANTED_FILES; do
-            echo "::error file=${FILES#./},title=Unwanted file detected::${FILES#./}"
-          done
-          if [[ -n $UNWANTED_FILES ]]
-          then
-            exit 1
-          else
-            echo No unwanted files detected
-          fi
+          check.sh $(pwd) $(pwd);
+          if [[ -s coding-style-reports.log ]]; then
+            exit 1;
+          fi;
+          exit 0;
+          echo "::set-output name=number_of_errors::$(grep -c 'Error' coding_style_reports.log)"
 
 
   compilation:
