[CHANGE] good steps coding style 4

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -19,24 +19,18 @@ jobs:
     container: ghcr.io/epitech/coding-style-checker:latest
     steps:
       - uses: actions/checkout@v3
-      
-      - name: "Check project coding style !"
-        run:
-          run: |
-run: |
-  if [[ -s coding-style-reports.log && $(grep -c 'Error' coding-style-reports.log) -gt 0 ]]; then
-    check.sh $(pwd) $(pwd)
-  fi;
-
-  if [[ -s coding-style-reports.log && $(grep -c 'Error' coding-style-reports.log) -gt 0 ]]; then
-    exit 1;
-  else
-    exit 0;
-  fi;
-
-  echo "::set-output name=number_of_errors::$(grep -c 'Error' coding-style-reports.log)"
-
-
+      - id: check_repo
+        run: |
+          UNWANTED_FILES=$(find . -type f -not -path "./git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.so" -or -name "*.gcno" -or -name "*.gcda" -or -name "*#" -or -name "#*" -or -name "*.gcov" -or -name "*pain_au_chocolat*")
+          for FILES in $UNWANTED_FILES; do
+            echo "::error file=${FILES#./},title=Unwanted file detected::${FILES#./}"
+          done
+          if [[ -n $UNWANTED_FILES ]]
+          then
+            exit 1
+          else
+            echo No unwanted files detected
+          fi
 
   compilation:
     name: "Checks compilation of binaries given !"
