[CHANGE] encore coding style

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -3,10 +3,10 @@ name: chocolatine
 on:
   push:
     branches-ignore:
-      - 'ga-ignore-*'
+    - "ga-ignore-*"
   pull_request:
     branches-ignore:
-      - 'ga-ignore-*'
+    - "ga-ignore-*"
 
 env:
   MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-LYN-2-1-chocolatine-safia.beaumale-mesmar"
@@ -14,55 +14,50 @@ env:
   ARGUMENTS: ""
 
 jobs:
-  check_repo:
-    name: "Checks if the repository is clean and void of any unwanted files (temp files, binary files, etc.)"
+  check_coding_style:
     runs-on: ubuntu-latest
-    container:
-      image: ghcr.io/epitech/coding-style-checker:latest
-
+    container: ghcr.io/epitech/coding-style-checker:latest
     steps:
       - uses: actions/checkout@v3
-      - id: check_repo
-        run: |
-          UNWANTED_FILES=$(find . -type f -not -path "./git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.so" -or -name "*.gcno" -or -name "*.gcda" -or -name "*#" -or -name "#*" -or -name "*.gcov" -or -name "*pain_au_chocolat*")
-          for FILES in $UNWANTED_FILES; do
-            echo "::error file=${FILES#./},title=Unwanted file detected::${FILES#./}"
-          done
-          if [[ -n $UNWANTED_FILES ]]
-          then
-            exit 1
-          else
-            echo No unwanted files detected
-          fi
+      
+      - name: "Check project coding style !"
+        run:
+          check.sh $(pwd) $(pwd);
+          if [[ -s coding-style-reports.log ]]; then
+            exit 1;
+          fi;
+          exit 0;
+          echo "::set-output name=number_of_errors::$(grep -c 'Error' coding_style_reports.log)"
 
-  check_program_compilation:
-    needs: [check_repo]
-    name: "Checks if make compil and test all binary listed in the ARGUMENTS variable"
+  check_compilation:
+    name: "Checks compilation of binaries given !"
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker:latest
+    needs: 
+      - check_coding_style
 
     steps:
       - uses: actions/checkout@v3
-      - id: check_program_compilation
-        run: make
+      - run: make
         timeout-minutes: 2
       - run: make clean
       - run: |
-          OIFS = $IFS
-          IFS = ','
+          OIFS=$IFS
+          IFS=','
           for x in $EXECUTABLES
             do
-              ./$x $ARGUMENTS
+              ./$x
             done
           IFS=$OIFS
 
-run_tests:
-    needs: [check_program_compilation]
-    name: "Runs tests with criterion"
+  run_tests:
+    name: "Runs criterion tests !"
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker:latest
+    needs: 
+      - check_compilation
 
     steps:
       - uses: actions/checkout@v3
@@ -71,18 +66,19 @@ run_tests:
         timeout-minutes: 2
 
   push_to_mirror:
-    needs: [run_tests]
-    if: ${{ github.event_name == 'push' }}
-    name: "Push all files to mirror specified"
+    name: "Push files to given mirror repo !"
     runs-on: ubuntu-latest
+    needs:
+      - run_tests
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      - uses: pixta-dev/repository-mirroring-action@v1
+
+      - uses: pixta-dev/repository-mirroring-action@main
         with:
           target_repo_url:
             ${{ env.MIRROR_URL }}
           ssh_private_key:
-            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+            ${{ secrets.GIT_SSH_KEY }}
