[CHANGE] coding style steps & v2

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -24,23 +24,28 @@ jobs:
       - uses: actions/checkout@v3
       - id: coding_style
         run: |
-          check.sh $(pwd) $(pwd);
-          if [[ -s coding-style-reports.log ]]; then
-            exit 1;
-          fi;
-          exit 0;
+          UNWANTED_FILES=$(find . -type f -not -path "./git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.so" -or -name "*.gcno" -or -name "*.gcda" -or -name "*#" -or -name "#*" -or -name "*.gcov" -or -name "*pain_au_chocolat*")
+          for FILES in $UNWANTED_FILES; do
+            echo "::error file=${FILES#./},title=Unwanted file detected::${FILES#./}"
+          done
+          if [[ -n $UNWANTED_FILES ]]
+          then
+            exit 1
+          else
+            echo No unwanted files detected
+          fi
 
 
   compilation:
+    needs: [coding_style]
     name: "Checks compilation of binaries given !"
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker:latest
-    needs: 
-      - coding_style
 
     steps:
       - uses: actions/checkout@v3
+      - id: compilation
       - run: make
         timeout-minutes: 2
       - run: make clean
@@ -49,17 +54,16 @@ jobs:
           IFS=','
           for x in $EXECUTABLES
             do
-              ./$x
+              ./$x $ARGUMENTS
             done
           IFS=$OIFS
 
   run_tests:
+    needs: [compilation]
     name: "Runs criterion tests !"
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker:latest
-    needs: 
-      - compilation
 
     steps:
       - uses: actions/checkout@v3
@@ -68,19 +72,18 @@ jobs:
         timeout-minutes: 2
 
   push_to_mirror:
+    needs: [run_tests]
+    if: ${{ github.event_name == 'push' }}
     name: "Push files to given mirror repo !"
     runs-on: ubuntu-latest
-    needs:
-      - run_tests
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v2
         with:
           fetch-depth: 0
-
-      - uses: pixta-dev/repository-mirroring-action@main
+      - uses: pixta-dev/repository-mirroring-action@v1
         with:
           target_repo_url:
             ${{ env.MIRROR_URL }}
           ssh_private_key:
-            ${{ secrets.GIT_SSH_KEY }}
+            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
