[CHANGE] encore coding style 100000

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -3,10 +3,10 @@ name: chocolatine
 on:
   push:
     branches-ignore:
-    - "ga-ignore-*"
+      - 'ga-ignore-*'
   pull_request:
     branches-ignore:
-    - "ga-ignore-*"
+      - 'ga-ignore-*'
 
 env:
   MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-LYN-2-1-chocolatine-safia.beaumale-mesmar"
@@ -14,69 +14,77 @@ env:
   ARGUMENTS: ""
 
 jobs:
-  check_coding_style:
+  check_repo:
+    name: "Checks if the repository is clean and void of any unwanted files (temp files, binary files, etc.)"
     runs-on: ubuntu-latest
-    container: ghcr.io/epitech/coding-style-checker:latest
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
+
     steps:
       - uses: actions/checkout@v3
-      
-      - name: "Check project coding style !"
-        run:
+      - id: check_repo
+        run: |
           check.sh $(pwd) $(pwd);
           if [[ -s coding-style-reports.log ]]; then
-            exit 1;
+            echo "::error file=coding-style-reports.log::Coding style check failed. Please fix the errors in the report file."
           fi;
-          exit 0;
-          echo "::set-output name=number_of_errors::$(grep -c 'Error' coding_style_reports.log)"
-
-  check_compilation:
-    name: "Checks compilation of binaries given !"
+  check_program_compilation:
+    needs: [check_repo]
+    name: "Checks compilation of binaries given"
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker:latest
-    needs: 
-      - check_coding_style
 
     steps:
       - uses: actions/checkout@v3
       - run: make
         timeout-minutes: 2
+        continue-on-error: true
+        shell: bash
+        env:
+          EXECUTABLES: ${{ env.EXECUTABLES }}
+
       - run: make clean
+
       - run: |
           OIFS=$IFS
           IFS=','
           for x in $EXECUTABLES
             do
-              ./$x
+              ./$x || echo "::error file=$x::Binary failed to execute. Please check the code."
             done
           IFS=$OIFS
-
   run_tests:
-    name: "Runs criterion tests !"
+    needs: [check_program_compilation]
+    name: "Runs tests with criterion"
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker:latest
-    needs: 
-      - check_compilation
 
     steps:
       - uses: actions/checkout@v3
       - id: run_tests
         run: make tests_run
         timeout-minutes: 2
+        continue-on-error: true
+        shell: bash
+        env:
+          EXECUTABLES: ${{ env.EXECUTABLES }}
 
+      - run: |
+          if [[ -s criterion_output.log ]]; then
+            echo "::error file=criterion_output.log::Unit tests failed. Please check the report file."
+          fi;
   push_to_mirror:
-    name: "Push files to given mirror repo !"
+    needs: [run_tests]
+    name: "Push to mirror"
     runs-on: ubuntu-latest
-    needs:
-      - run_tests
-
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
-      - uses: pixta-dev/repository-mirroring-action@main
+      - uses: pixta-dev/repository-mirroring-action@v1
         with:
           target_repo_url:
             ${{ env.MIRROR_URL }}
